package MoodleTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ProfileFieldEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ProfileFieldEnum() {
    super(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb40471bL, "ProfileFieldEnum", "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2441660594466604827");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_username_0 = new EnumerationDescriptor.MemberDescriptor("username", "username", 0x21e2855fcb40471cL, "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2441660594466604828");
  private final EnumerationDescriptor.MemberDescriptor myMember_firstname_0 = new EnumerationDescriptor.MemberDescriptor("firstname", "first name", 0x21e2855fcb40471dL, "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2441660594466604829");
  private final EnumerationDescriptor.MemberDescriptor myMember_lastname_0 = new EnumerationDescriptor.MemberDescriptor("lastname", "last name", 0x21e2855fcb404720L, "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2441660594466604832");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb40471bL, 0x21e2855fcb40471cL, 0x21e2855fcb40471dL, 0x21e2855fcb404720L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_username_0, myMember_firstname_0, myMember_lastname_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return myMember_username_0;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "username":
        return myMember_username_0;
      case "firstname":
        return myMember_firstname_0;
      case "lastname":
        return myMember_lastname_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
