package MoodleTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptor;
import jetbrains.mps.smodel.runtime.ConstrainedStringDatatypeDescriptorImpl;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import jetbrains.mps.smodel.runtime.DataTypeDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptExerciseWithSubname = createDescriptorForExerciseWithSubname();
  /*package*/ final ConceptDescriptor myConceptExerciseWithTag = createDescriptorForExerciseWithTag();
  /*package*/ final ConceptDescriptor myConceptExercises = createDescriptorForExercises();
  /*package*/ final ConceptDescriptor myConceptMoodleTest = createDescriptorForMoodleTest();
  /*package*/ final ConceptDescriptor myConceptMoodleTests = createDescriptorForMoodleTests();
  /*package*/ final ConceptDescriptor myConceptQuizUser = createDescriptorForQuizUser();
  /*package*/ final ConceptDescriptor myConceptQuizUsers = createDescriptorForQuizUsers();
  /*package*/ final ConceptDescriptor myConceptSettings = createDescriptorForSettings();
  /*package*/ final EnumerationDescriptor myEnumerationQuizUserConditionEnum = new EnumerationDescriptor_QuizUserConditionEnum();
  /*package*/ final EnumerationDescriptor myEnumerationQuizUserFieldEnum = new EnumerationDescriptor_QuizUserFieldEnum();
  /*package*/ final EnumerationDescriptor myEnumerationQuizUserSeparatorEnum = new EnumerationDescriptor_QuizUserSeparatorEnum();
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeAttemptsType = new ConstrainedStringDatatypeDescriptorImpl(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e53a6cfL, "AttemptsType", "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/8902074227500492495", "^(?:[1-9]|10|unlimited)$");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeCharacter = new ConstrainedStringDatatypeDescriptorImpl(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21858de44a95f54L, "Character", "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/150968299174846292", "^[a-zA-Z]{1,30}$");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeExerciseCountType = new ConstrainedStringDatatypeDescriptorImpl(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e53fb1dL, "ExerciseCountType", "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/8902074227500514077", "^(?:100|[1-9][0-9]?)$");
  /*package*/ final ConstrainedStringDatatypeDescriptor myCSDatatypeGradeType = new ConstrainedStringDatatypeDescriptorImpl(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21858de44984595L, "GradeType", "r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/150968299173725589", "^(10(\\.00?)?|[0-9](\\.[0-9]{1,2})?)$");
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExerciseWithSubname, myConceptExerciseWithTag, myConceptExercises, myConceptMoodleTest, myConceptMoodleTests, myConceptQuizUser, myConceptQuizUsers, myConceptSettings);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.ExerciseWithSubname:
        return myConceptExerciseWithSubname;
      case LanguageConceptSwitch.ExerciseWithTag:
        return myConceptExerciseWithTag;
      case LanguageConceptSwitch.Exercises:
        return myConceptExercises;
      case LanguageConceptSwitch.MoodleTest:
        return myConceptMoodleTest;
      case LanguageConceptSwitch.MoodleTests:
        return myConceptMoodleTests;
      case LanguageConceptSwitch.QuizUser:
        return myConceptQuizUser;
      case LanguageConceptSwitch.QuizUsers:
        return myConceptQuizUsers;
      case LanguageConceptSwitch.Settings:
        return myConceptSettings;
      default:
        return null;
    }
  }

  @Override
  public Collection<DataTypeDescriptor> getDataTypeDescriptors() {
    return Arrays.asList(myEnumerationQuizUserConditionEnum, myEnumerationQuizUserFieldEnum, myEnumerationQuizUserSeparatorEnum, myCSDatatypeAttemptsType, myCSDatatypeCharacter, myCSDatatypeExerciseCountType, myCSDatatypeGradeType);
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForExerciseWithSubname() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "ExerciseWithSubname", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x223179e4c7c4ff1eL);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2463884494659452702");
    b.version(3);
    b.property("count", 0x223179e4c7c50397L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e53fb1dL)).origin("2463884494659453847").done();
    b.property("subname", 0x223179e4c7c504ebL).type(PrimitiveTypeId.STRING).origin("2463884494659454187").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExerciseWithTag() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "ExerciseWithTag", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x223179e4c7c4f2a6L);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2463884494659449510");
    b.version(3);
    b.property("count", 0x223179e4c7c4f934L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e53fb1dL)).origin("2463884494659451188").done();
    b.property("tag", 0x223179e4c7c4fa54L).type(PrimitiveTypeId.STRING).origin("2463884494659451476").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForExercises() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "Exercises", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97718d1L);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/6569387237471361233");
    b.version(3);
    b.aggregate("ContentWithSubname", 0x223179e4c7c51481L).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x223179e4c7c4ff1eL).optional(true).ordered(true).multiple(true).origin("2463884494659458177").done();
    b.aggregate("ContentWithTag", 0x223179e4c7cafc69L).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x223179e4c7c4f2a6L).optional(true).ordered(true).multiple(true).origin("2463884494659845225").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoodleTest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "MoodleTest", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97557e4L);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/6569387237471246308");
    b.version(3);
    b.property("title", 0x5b2b26e2e977679bL).type(PrimitiveTypeId.STRING).origin("6569387237471381403").done();
    b.property("questionCategory", 0x7b8a85583e38c5c4L).type(PrimitiveTypeId.STRING).origin("8902074227498730948").done();
    b.aggregate("Exercises", 0x5b2b26e2e9772576L).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97718d1L).optional(false).ordered(true).multiple(false).origin("6569387237471364470").done();
    b.aggregate("QuizUsers", 0x247af2bf756f1d9dL).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x247af2bf756de6afL).optional(false).ordered(true).multiple(false).origin("2628680236646997405").done();
    b.aggregate("Settings", 0x7b8a85583e43e55cL).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e3bb8deL).optional(false).ordered(true).multiple(false).origin("8902074227499459932").done();
    b.alias("moodle test");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoodleTests() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "MoodleTests", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x223179e4c7bf010eL);
    b.class_(false, false, true);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2463884494659059982");
    b.version(3);
    b.aggregate("Content", 0x223179e4c7bf049dL).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97557e4L).optional(false).ordered(true).multiple(true).origin("2463884494659060893").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuizUser() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "QuizUser", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb403dbbL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2441660594466602427");
    b.version(3);
    b.property("field", 0x21e2855fcb403fc5L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb40471bL)).origin("2441660594466602949").done();
    b.property("condition", 0x21e2855fcb404237L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb404915L)).origin("2441660594466603575").done();
    b.alias("quiz user");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForQuizUsers() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "QuizUsers", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x247af2bf756de6afL);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/2628680236646917807");
    b.version(3);
    b.property("separator", 0x21e2855fcb45c418L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb45c553L)).origin("2441660594466964504").done();
    b.aggregate("QuizUser", 0x247af2bf756deebbL).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21e2855fcb403dbbL).optional(true).ordered(true).multiple(true).origin("2628680236646919867").done();
    b.alias("students");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForSettings() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "Settings", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e3bb8deL);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/8902074227498924254");
    b.version(3);
    b.property("shuffle", 0x21858de4499e82eL).type(PrimitiveTypeId.BOOLEAN).origin("150968299173832750").done();
    b.property("attempts", 0x21858de4498eb5aL).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x7b8a85583e53a6cfL)).origin("150968299173768026").done();
    b.property("passgrade", 0x21858de4498ccd6L).type(MetaIdFactory.dataTypeId(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x21858de44984595L)).origin("150968299173760214").done();
    return b.create();
  }
}
