package MoodleTests.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptExercise = createDescriptorForExercise();
  /*package*/ final ConceptDescriptor myConceptMoodleTest = createDescriptorForMoodleTest();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptExercise, myConceptMoodleTest);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Exercise:
        return myConceptExercise;
      case LanguageConceptSwitch.MoodleTest:
        return myConceptMoodleTest;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForExercise() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "Exercise", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97718d1L);
    b.class_(false, false, false);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/6569387237471361233");
    b.version(3);
    b.property("count", 0x5b2b26e2e9771ac1L).type(PrimitiveTypeId.INTEGER).origin("6569387237471361729").done();
    b.property("subname", 0x5b2b26e2e9771f21L).type(PrimitiveTypeId.STRING).origin("6569387237471362849").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMoodleTest() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("MoodleTests", "MoodleTest", 0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97557e4L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:ac90c03e-a5f2-4acd-af46-01188a354211(MoodleTests.structure)/6569387237471246308");
    b.version(3);
    b.property("coursId", 0x5b2b26e2e9770cffL).type(PrimitiveTypeId.INTEGER).origin("6569387237471358207").done();
    b.property("title", 0x5b2b26e2e977679bL).type(PrimitiveTypeId.STRING).origin("6569387237471381403").done();
    b.aggregate("content", 0x5b2b26e2e9772576L).target(0x54f7c48843b442ecL, 0xa6a7b6ba91a8bda2L, 0x5b2b26e2e97718d1L).optional(true).ordered(true).multiple(true).origin("6569387237471364470").done();
    return b.create();
  }
}
